install:
- wget https://github.com/gohugoio/hugo/releases/download/v0.68.1/hugo_0.68.1_Linux-64bit.deb
- sudo dpkg -i  hugo* .deb
-hugo version
before script :
-rm -rf public
script:
-hugo
branches:
    only:
    -master